create table if not exists public.reservations (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  car text not null,
  package text not null,
  car_size text not null,
  extras text[] not null default '{}',
  estimated_price integer,
  reservation_date date not null,
  reservation_time time not null,
  notes text,
  created_at timestamptz not null default now(),
  constraint reservations_reservation_date_reservation_time_key
    unique (reservation_date, reservation_time)
);

alter table public.reservations enable row level security;
